### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by safwansamsudeen** [aatmanvaidya/aatmanvaidya.github.io#2]
Hey, 

I just wanted to let you know of a typo in your website.
<img width="830" alt="image" src="https://github.com/user-attachments/assets/f3b8ece8-3883-43a1-abb2-fcd2b85edea6">

I look forward to contributing to Tattle over the upcoming months, and hopefully have the pleasure of working with you!

**Comment by aatmanvaidya** [comment]
Hey, 
thank you for pointing that out, have fixed it. Looking forward to interact with you as well!
